POST http://localhost:3000/gerente/login
Content-Type: application/json

{
  "user": "usuario",
  "password": "contra"
}

### prueba get
GET http://localhost:3000/gerente



### obtener boletos
GET http://localhost:3000/boletos/precios/2

### obtener boletos por tipo de proyeccion

GET http://localhost:3000/boletos/precios/1

### create new sala
POST http://localhost:3000/salas/nuevo
Content-Type: application/json

{
  "numeroSala": 93,
  "capacidad": 156
}

### get all movies
GET http://localhost:3000/peliculas/emision

### obtener numero sala
GET http://localhost:3000/boletos/proyecciones/2

### get seats
GET http://localhost:3000/boletos/asientos/2
