POST http://localhost:3000/gerente/login
Content-Type: application/json

{
  "user": "carlos_flores12",
  "password": "superContra"
}

### prueba get
GET http://localhost:3000/gerente



### obtener boletos
GET http://localhost:3000/boletos/precios/2

### obtener boletos por tipo de proyeccion

GET http://localhost:3000/boletos/precios/1

### create new sala
POST http://localhost:3000/salas/nuevo
Content-Type: application/json

{
  "numeroSala": 93,
  "capacidad": 156
}

### get all movies
GET http://localhost:3000/peliculas/emision

### obtener numero sala
GET http://localhost:3000/boletos/proyecciones/2

### get seats
GET http://localhost:3000/boletos/asientos/2

### create superAdmin
POST http://localhost:3000/gerente/nuevo
Content-Type: application/json

{
  "isAdmin": 1,
  "persona": {
    "DNI": "0801200415962",
    "Nombre1": "Juan",
    "Nombre2": "Carlos",
    "Apellido1": "Flores",
    "Apellido2": "Trujillo",
    "Correo": "carlos.flores@gmail.com"
  },
  "empleado": {
    "ID_Cargo": 1,
    "ID_Sucursal": 1,
    "ID_Contrato": 1,
    "Salario": 1200.50,
    "ID_Jornada": 3,
    "Numero_Empleado": 12,
    "Habilitado": 1
  },
  "admin": {
    "Usuario": "carlos_flores12",
    "Contrasena": "superContra",
    "Habilitado": 1
  }
}
